### ISSUE TITLE
Deprecate #open, use #readyState

### ISSUE THREAD

**Issue by rauchg** [LearnBoost/websocket.io#18]

**Comment by nicokaiser** [comment]
Can you have a look at this and tell me if this is what you meant?

https://github.com/nicokaiser/websocket.io/commit/a476101ff09dc5a99be13c9d26b01f1f6cfcebaf

I implemented wsio.Socket.readyState instead of wsio.Socket.open, and the "connection" event is emitted async, as the hybi protocol (ws) works with a callback...

I have to test it / analyze control flows and see if it's correct...
