### ISSUE TITLE
client tracking bug in handleUpgrade

### ISSUE THREAD

**Issue by railnerd** [LearnBoost/websocket.io#41]
Server.prototype.handleUpgrade has a nasty bug with regard to client tracking.  It uses "i" which is an outside of scope variable— seems like this might be just a typo of just some late night coding.

```
  client.on('close', function () {
    self.clients[i] = null;
    self.clientsCount--;
  });
```

Since we're sure that client is inside of the clients array, a quick fix to the bug would be to do the following:

```
  client.on('close', function () {
    clients.splice(clients.indexOf(client),1);
    self.clientsCount--;
  });
```

**Comment by rauchg** [comment]
That's awful.

**Comment by rauchg** [comment]
Although client tracking usage is discouraged, I forgot to add it to the README

**Comment by rauchg** [comment]
It actually looks like it's potentially a race condition instead.

**Comment by rauchg** [comment]
@nicokaiser
I cleaned up some of your `clientTracking` work here: https://github.com/LearnBoost/websocket.io/compare/fix-tracking
Is there a chance for a race condition here? Can a client reserve a `i` and then by the time `open` fires the `i` is a different client?

**Comment by railnerd** [comment]
I had assumed the use of "i" was a typo, not a reference to the other "i" in the module.

**Comment by railnerd** [comment]
actually, the other issue is that you end up with a clients array full of nulls. Couldn't you track clients using an associative array instead?

```
if (self.options.clientTracking) {
  self.clients[client] = client;
  self.clientsCount++;
  client.on('close', function () {
    delete self.clients[client];
    self.clientsCount--;
  });
}
```

**Comment by railnerd** [comment]
(and yes I agree that fix was god awful)  ;-)

**Comment by rauchg** [comment]
No I meant an awful bug haha!! Thanks for reporting this

**Comment by railnerd** [comment]
BTW: I still think there is a leak where the clients array never shrinks. I'm a fairly recent student of Javascript so apologies if I get any of this wrong, I'm an OCD C programmer by day— I started playing with node & socket.io on a hobby project and have been smitten— haven't had this much fun programming since 5th grade (and trust me, that was a LONG time ago).

**Comment by rauchg** [comment]
Yes. We should `delete` instead of setting to null

**Comment by rauchg** [comment]
And `clients` should be a `{}`

**Comment by ruxkor** [comment]
While inspecting the same blocks because of [issue 42](https://github.com/LearnBoost/websocket.io/issues/42), I think that using an object is actually not the best solution for it:

While the access to single `server.clients` would be efficient, slicing, etc. would be much more cumbersome. The other point is that even with the object usage, `i` would steadily increase.

In [commit 68f8258f97](https://github.com/ruxkor/websocket.io/commit/68f8258f97aaaf2120445c45b67a5ef0fd335502) in my fork I addressed this issue by
- saving the closed connections (i.e. the ones that will be set to `null`) in an array, and
- reusing these indices when a new connection is created

this way, the maximum array size is bound to the maximum number of concurrent connections, which seems to be the optimal tradeoff for my uses.

**Comment by rauchg** [comment]
I like that approach, would you mind submitting a pull request? Thanks!

**Comment by ruxkor** [comment]
here it is :) the changes are only about the array filling, without your `fix-tracking` branch (i.e. it differs from the commit I linked to in the last comment).
